version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    volumes:
      - ./backend:/app

  frontend:
    image: node:22
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm start -- --host 0.0.0.0
    ports:
      - "4200:4200"
